<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => '和',
    'Append Line Break' => '追加换行符',
    'Block Quote' => '块引用',
    'Bold' => '加粗',
    'Bulleted List' => '项目列表',
    'Code Block' => '代码块',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => '定义列表',
    'Footnote' => '脚注',
    'HTML' => 'HTML',
    'Heading' => '标题',
    'Heading {n} Style' => '标题 {n} 样式',
    'Horizontal Line' => '水平线',
    'Image' => '图片',
    'Indent Text' => '缩进文本',
    'Inline Code' => '行内代码',
    'Italic' => '斜体',
    'Loading Preview ' => '正在加载预览',
    'markdown-export' => 'markdown-导出',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown 导出{line} *由 {class} 于 {date} 生成',
    'No content to display' => '无内容可显示',
    'Numbered List' => '编号列表',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants 排版',
    'Paragraph' => '段落',
    'Preview' => '预览',
    'Preview formatted text' => '预览格式化文本',
    'Export' => '导出',
    'Save content' => '保存内容',
    'Save as HTML' => '保存为 HTML',
    'Save as text' => '保存为文本',
    'Text' => '文本',
    'Toggle full screen' => '切换全屏',
    'Unindent Text' => '取消缩进文本',
    'URL/Link' => 'URL/链接',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} 要撤销/重做，请按 {keys}。您还可以通过再次单击按钮来撤销大多数按钮操作。',
    '{bullet} You may use {link} syntax.' => '{bullet} 您可以使用 {link} 语法。',
];
